---
version: '3.8'
services:
  assembly:
    build:
      dockerfile: assembly.Dockerfile
    volumes:
      - type: bind
        source: /tmp/folder_common
        target: /tmp/folder_common
  prod:
    build:
      dockerfile: prod.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: /tmp/folder_common
        target: /tmp/folder_common
    depends_on:
      - assembly
