---
version: '3.8'
services:
  assembly:
    build:
      dockerfile: assembly.Dockerfile
    volumes:
      - type: volume
        source: folder_common
        target: /tmp/boxfuse-sample-java-war-hello/target/
  prod:
    build:
      dockerfile: prod.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: volume
        source: folder_common
        target: /opt/tomcat/webapps/
    depends_on:
      - assembly
volumes:
  folder_common:
