---
version: '3.8'
services:
  assembly:
    build:
      dockerfile: assembly.Dockerfile
    volumes:
      - type: volume
        source: folder_common
        target: /tmp/boxfuse-sample-java-war-hello/target/
  prod:
    #build:
    #  dockerfile: prod.Dockerfile
    image: 'woahbase/alpine-tomcat:x86_64'
    hostname: 'tomcat'
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: folder_common
        target: /opt/tomcat/webapps/
    depends_on:
      - assembly
volumes:
  folder_common:
