---
version: '3'
services:
  assembly:
    build:
      dockerfile: assembly.Dockerfile
    volumes:
      - '/var/folder_common:/var/folder_common'
  prod:
    build:
      dockerfile: prod.Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/folder_common:/var/folder_common'
    depends_on:
      - assembly
